"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./script/BAT.py']
APP_NAME = "BAT"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'iconfile': '/Users/syungsan/Documents/IDEAProjects/PyBAT/data/Thesquid.ink-Free-Flat-Sample-Support.icns',
    'strip': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "BATってなんの略",
        'CFBundleIdentifier': "",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': "Copyright © 2020, Tadano Laboratory, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# Build Command
# rm -rf dist/ build/
# python setup.py py2app --packages=PIL
